### ISSUE TITLE
Error: Unexpected comment

### ISSUE THREAD

**Issue by nirazul** [mnbroatch/yarn-bound#6]
I'm trying out yarn-bound for a new web project I'm currently starting to check if it's a suitable path for me to take. For the moment the project looks promising and I'm very happy to use it!

However there are some bumps in the road. I'm currently working with the [test yarn file](https://docs.yarnspinner.dev/unity-sample-projects/example-project-1#start.yarn) from YarnSpinner.

When I'm feeding it into YarnBound, I'm receiving the following error:

```
Uncaught (in promise) Parse error on line 22: Unexpected 'Comment'
```

When I delete the comment (line 25 and 26) there is no error.

Could you have a look at it? Are comments currently unsupported?

**Comment by marcusround** [comment]
This is a bug trigger by the comments being at a different level of indentation to the line above them. I think this is an oversight in the bondage parser.
If you adjust the lines
```
    -> Ugh, no.
<<endif>>
// if they didn't offer to play a game, or they did but you said no,
// then they don't like you now
<<jump BadEnding>>
```
to this
```
    -> Ugh, no.
<<endif>>
    // if they didn't offer to play a game, or they did but you said no,
    // then they don't like you now
<<jump BadEnding>>
``` 
Then you will not get an error.

**Comment by mnbroatch** [comment]
Sorry it took so long to get to this! The latest version has better support for comments. Thanks!

**Comment by nirazul** [comment]
no worries, and thank you! 😃
